# Generated by Django 2.0 on 2020-04-28 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='video',
            name='channels',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.Channels', verbose_name='专题'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.Tags', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='channels',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.Channels', verbose_name='专题'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.Tags', verbose_name='标签'),
        ),
    ]
